### ISSUE TITLE
Auth: Foster can log out

### ISSUE THREAD

**Issue by danblau** [rubyforgood/shelter-assist#54]
**How does it work now?**
Currently, it is not possible for a foster to log out of their account. After signing in, the "login" button is visible on the foster app. 

**How should it work?**
- After logging in, a foster should be able to log out of their account using a "Log Out" button
- After logging in, the "Login" button should be hidden

**Acceptance Criteria**

- Verify that a foster can log out after signing in
- Verify that after signing in the login button is hidden

**Comment by wadewinningham** [comment]
Merged in https://github.com/rubyforgood/shelter-assist/pull/73
